// archivo: peliculasData.jsx o peliculasData.js

/**
 * Objeto exportable (Array de películas) que contiene 20 títulos basados en libros,
 * con detalles completos para su uso en una aplicación de React.
 */
export const peliculasBasadasEnLibros = [
  {
    id: 1,
    nombre: "El Señor de los Anillos: La Comunidad del Anillo (2001)",
    rangoEdad: "PG-13 (Mayores de 13)",
    autor: "J.R.R. Tolkien",
    reseña: "Una adaptación monumental que capturó la épica fantasía de la Tierra Media con una fidelidad visual y emocional asombrosa.",
    descripcionPelicula: "Frodo Bolsón hereda un anillo que debe ser destruido en el Monte del Destino para salvar a la Tierra Media de la oscuridad. Lidera una Comunidad de nueve compañeros en un peligroso viaje.",
    recomendacion: "Imprescindible para los amantes de la fantasía, la aventura y la mitología. Ideal para una maratón épica.",
    detallesPelicula: "Dirigida por Peter Jackson. Ganadora de 4 Premios de la Academia. Conocida por sus efectos especiales innovadores para la época.",
    duracionPelicula: "2h 58m (Versión extendida: 3h 48m)",
    imagenURL: "https://ejemplo.com/imagenes/el-senor-de-los-anillos.jpg"
  },
  {
    id: 2,
    nombre: "El Padrino (1972)",
    rangoEdad: "R (Restringido)",
    autor: "Mario Puzo",
    reseña: "Considerada una de las mejores películas de la historia, es un estudio profundo y oscuro de la familia, el poder y la corrupción en la mafia.",
    descripcionPelicula: "La crónica de la familia mafiosa Corleone bajo la dirección de Vito Corleone, centrándose en la transformación de su hijo, Michael Corleone, en un despiadado jefe de la mafia.",
    recomendacion: "Obligatoria para fans del cine de gánsteres y dramas familiares complejos.",
    detallesPelicula: "Dirigida por Francis Ford Coppola. Ganadora de 3 Premios de la Academia (incluyendo Mejor Película).",
    duracionPelicula: "2h 55m",
    imagenURL: "https://ejemplo.com/imagenes/el-padrino.jpg"
  },
  {
    id: 3,
    nombre: "Harry Potter y el Prisionero de Azkaban (2004)",
    rangoEdad: "PG (Guía paternal sugerida)",
    autor: "J.K. Rowling",
    reseña: "A menudo citada como la mejor de la saga. Es más oscura, visualmente inventiva y marca la transición de las películas a un tono más maduro.",
    descripcionPelicula: "Harry Potter se enfrenta a la fuga de Sirius Black, un supuesto asesino de la prisión de magos de Azkaban, mientras aprende más sobre el pasado de sus padres.",
    recomendacion: "Para los fans de la fantasía que disfrutan de misterios con un toque de terror gótico.",
    detallesPelicula: "Dirigida por Alfonso Cuarón. Introdujo un estilo visual más cinematográfico y artístico a la franquicia.",
    duracionPelicula: "2h 22m",
    imagenURL: "https://ejemplo.com/imagenes/harry-potter-azkaban.jpg"
  },
  {
    id: 4,
    nombre: "Matar a un Ruiseñor (1962)",
    rangoEdad: "NR (No Clasificado, apta para toda la familia)",
    autor: "Harper Lee",
    reseña: "Un poderoso drama legal y social. La actuación de Gregory Peck es icónica, elevando temas de injusticia racial y moralidad.",
    descripcionPelicula: "Un abogado sureño, Atticus Finch, defiende a un hombre negro acusado falsamente de violar a una mujer blanca, mientras sus hijos observan la profunda discriminación de su comunidad.",
    recomendacion: "Excelente para reflexionar sobre la historia de los derechos civiles y la integridad moral.",
    detallesPelicula: "Dirigida por Robert Mulligan. Ganadora de 3 Premios de la Academia. Considerada un clásico del cine estadounidense.",
    duracionPelicula: "2h 9m",
    imagenURL: "https://ejemplo.com/imagenes/matar-a-un-ruisenor.jpg"
  },
  {
    id: 5,
    nombre: "Blade Runner (1982)",
    rangoEdad: "R (Restringido)",
    autor: "Philip K. Dick",
    reseña: "Un hito del cine de ciencia ficción. Su estética *neo-noir* y sus profundas preguntas filosóficas sobre la humanidad han influido en innumerables obras.",
    descripcionPelicula: "En un futuro distópico, un 'blade runner' (Rick Deckard) tiene la misión de cazar a replicantes genéticamente modificados que han regresado a la Tierra.",
    recomendacion: "Imprescindible para los fans de la ciencia ficción y el cine con dilemas existenciales.",
    detallesPelicula: "Dirigida por Ridley Scott. Basada en la novela *¿Sueñan los androides con ovejas eléctricas?*. Existen varias versiones del director.",
    duracionPelicula: "1h 57m (Corte del Director)",
    imagenURL: "https://ejemplo.com/imagenes/blade-runner.jpg"
  },
  {
    id: 6,
    nombre: "El Resplandor (1980)",
    rangoEdad: "R (Restringido)",
    autor: "Stephen King",
    reseña: "Una obra maestra del terror psicológico. La dirección de Kubrick y la actuación de Nicholson crean una atmósfera de claustrofobia y locura inolvidable.",
    descripcionPelicula: "Un escritor y su familia se mudan a un hotel aislado para cuidarlo durante el invierno, donde una fuerza maligna intenta volver loco al padre.",
    recomendacion: "Para aquellos que disfrutan del terror que se enfoca más en la psique que en el *gore*.",
    detallesPelicula: "Dirigida por Stanley Kubrick. Aunque el autor no la considera fiel, es una película icónica.",
    duracionPelicula: "1h 59m",
    imagenURL: "https://ejemplo.com/imagenes/el-resplandor.jpg"
  },
  {
    id: 7,
    nombre: "Cadena Perpetua (1994)",
    rangoEdad: "R (Restringido)",
    autor: "Stephen King",
    reseña: "Una historia conmovedora sobre la esperanza, la amistad y la perseverancia. Una de las películas mejor valoradas de todos los tiempos.",
    descripcionPelicula: "Un banquero es condenado por error por el asesinato de su esposa y su amante. En prisión, forja una amistad con otro recluso y planea su fuga durante décadas.",
    recomendacion: "Altamente recomendada por su guion, actuaciones y mensaje de optimismo.",
    detallesPelicula: "Dirigida por Frank Darabont. Basada en la novela corta *Rita Hayworth y la redención de Shawshank*.",
    duracionPelicula: "2h 22m",
    imagenURL: "https://ejemplo.com/imagenes/cadena-perpetua.jpg"
  },
  {
    id: 8,
    nombre: "Orgullo y Prejuicio (2005)",
    rangoEdad: "PG (Guía paternal sugerida)",
    autor: "Jane Austen",
    reseña: "Una vibrante y visualmente hermosa adaptación de la novela clásica. Captura la tensión romántica y el ingenio de la obra original.",
    descripcionPelicula: "En la Inglaterra del siglo XIX, las cinco hermanas Bennet navegan por las presiones sociales, centrándose en la relación tumultuosa entre Elizabeth Bennet y el Sr. Darcy.",
    recomendacion: "Para los amantes del romance de época, los dramas de vestuario y las historias de Jane Austen.",
    detallesPelicula: "Dirigida por Joe Wright. Protagonizada por Keira Knightley. Famosa por su cinematografía y ambientación.",
    duracionPelicula: "2h 9m",
    imagenURL: "https://ejemplo.com/imagenes/orgullo-y-prejuicio.jpg"
  },
  {
    id: 9,
    nombre: "Psicosis (1960)",
    rangoEdad: "R (Restringido, original), PG (versiones posteriores)",
    autor: "Robert Bloch",
    reseña: "Un clásico de terror y suspense que revolucionó el género. La dirección de Hitchcock mantiene una tensión constante e incómoda.",
    descripcionPelicula: "Una secretaria que roba dinero se esconde en un motel regentado por un joven tímido bajo el dominio de su madre.",
    recomendacion: "Esencial para cualquier cinéfilo, especialmente para estudiar la técnica narrativa en el cine.",
    detallesPelicula: "Dirigida por Alfred Hitchcock. La famosa escena de la ducha es uno de los momentos más icónicos del cine.",
    duracionPelicula: "1h 49m",
    imagenURL: "https://ejemplo.com/imagenes/psicosis.jpg"
  },
  {
    id: 10,
    nombre: "Forrest Gump (1994)",
    rangoEdad: "PG-13 (Mayores de 13)",
    autor: "Winston Groom",
    reseña: "Una película emotiva y memorable que utiliza la vida de su protagonista para repasar medio siglo de historia estadounidense.",
    descripcionPelicula: "La vida de Forrest Gump, un hombre con un coeficiente intelectual por debajo del promedio, que participa en varios de los eventos históricos más significativos de los EE. UU.",
    recomendacion: "Un drama tierno y divertido con un gran corazón, apto para ver en familia.",
    detallesPelicula: "Dirigida por Robert Zemeckis. Ganadora de 6 Premios de la Academia (incluyendo Mejor Película).",
    duracionPelicula: "2h 22m",
    imagenURL: "https://ejemplo.com/imagenes/forrest-gump.jpg"
  },
  {
    id: 11,
    nombre: "Dune (2021)",
    rangoEdad: "PG-13 (Mayores de 13)",
    autor: "Frank Herbert",
    reseña: "Una adaptación visualmente impresionante y ambiciosa. Logra capturar la escala épica y la complejidad política de la novela de ciencia ficción.",
    descripcionPelicula: "El joven Paul Atreides viaja al planeta desierto Arrakis, el único productor de la especia más valiosa del universo, viéndose envuelto en una guerra por su control.",
    recomendacion: "Excelente para los fans de la ciencia ficción compleja, las historias de poder y el diseño visual impactante.",
    detallesPelicula: "Dirigida por Denis Villeneuve. Primer parte de una saga planeada.",
    duracionPelicula: "2h 35m",
    imagenURL: "https://ejemplo.com/imagenes/dune-2021.jpg"
  },
  {
    id: 12,
    nombre: "El Club de la Lucha (1999)",
    rangoEdad: "R (Restringido)",
    autor: "Chuck Palahniuk",
    reseña: "Un *thriller* oscuro y satírico. Es un comentario mordaz sobre el consumismo, la masculinidad y el desasosiego moderno.",
    descripcionPelicula: "Un oficinista insomne se encuentra con un fabricante de jabones carismático y forma un club de lucha subterráneo que se transforma en algo mucho más grande.",
    recomendacion: "Para el público que disfruta de películas con giros argumentales y una crítica social intensa.",
    detallesPelicula: "Dirigida por David Fincher. Basada en la novela homónima.",
    duracionPelicula: "2h 19m",
    imagenURL: "https://ejemplo.com/imagenes/club-de-la-lucha.jpg"
  },
  {
    id: 13,
    nombre: "La Naranja Mecánica (1971)",
    rangoEdad: "R (Restringido)",
    autor: "Anthony Burgess",
    reseña: "Una obra controvertida y brillante. Es una sátira brutal sobre el libre albedrío, la delincuencia juvenil y el control estatal.",
    descripcionPelicula: "En una Inglaterra futurista, Alex y su banda se dedican a la 'ultraviolencia' antes de que Alex sea capturado y sometido a una técnica experimental de reeducación.",
    recomendacion: "Para espectadores maduros interesados en la sátira distópica y el cine provocador.",
    detallesPelicula: "Dirigida por Stanley Kubrick. La película causó gran controversia en su estreno.",
    duracionPelicula: "2h 16m",
    imagenURL: "https://ejemplo.com/imagenes/naranja-mecanica.jpg"
  },
  {
    id: 14,
    nombre: "El Diario de Noa (The Notebook) (2004)",
    rangoEdad: "PG-13 (Mayores de 13)",
    autor: "Nicholas Sparks",
    reseña: "Uno de los dramas románticos más populares y lacrimógenos de la última década. Un romance intenso y con giros emocionales.",
    descripcionPelicula: "En los años 40, un chico humilde se enamora perdidamente de una chica rica, a pesar de la desaprobación de sus padres.",
    recomendacion: "Ideal para una noche de cine romántico y melancólico.",
    detallesPelicula: "Dirigida por Nick Cassavetes. Protagonizada por Ryan Gosling y Rachel McAdams.",
    duracionPelicula: "2h 3m",
    imagenURL: "https://ejemplo.com/imagenes/el-diario-de-noa.jpg"
  },
  {
    id: 15,
    nombre: "Mujercitas (Little Women) (2019)",
    rangoEdad: "PG (Guía paternal sugerida)",
    autor: "Louisa May Alcott",
    reseña: "Una adaptación moderna y fresca que honra el espíritu del clásico. Destaca por su ritmo ágil y un reparto brillante.",
    descripcionPelicula: "Sigue la vida de cuatro hermanas (Jo, Meg, Amy y Beth March) en la Nueva Inglaterra posterior a la Guerra Civil, mientras persiguen sus sueños.",
    recomendacion: "Perfecta para ver en familia, especialmente para quienes aprecian historias sobre ambición y hermandad.",
    detallesPelicula: "Dirigida por Greta Gerwig. Nominada a 6 Premios de la Academia.",
    duracionPelicula: "2h 15m",
    imagenURL: "https://ejemplo.com/imagenes/mujercitas-2019.jpg"
  },
  {
    id: 16,
    nombre: "El Exorcista (1973)",
    rangoEdad: "R (Restringido)",
    autor: "William Peter Blatty",
    reseña: "Un referente absoluto del cine de terror. La película va más allá del susto fácil, profundizando en temas de fe y desesperación.",
    descripcionPelicula: "Una actriz busca ayuda para su hija de 12 años, que parece estar poseída por una entidad demoníaca, recurriendo a dos sacerdotes para un exorcismo.",
    recomendacion: "Solo para los amantes del terror clásico y psicológico. No apta para sensibles.",
    detallesPelicula: "Dirigida por William Friedkin. Ganadora de 2 Premios de la Academia. Basada en hechos que inspiraron el libro.",
    duracionPelicula: "2h 2m",
    imagenURL: "https://ejemplo.com/imagenes/el-exorcista.jpg"
  },
  {
    id: 17,
    nombre: "El Silencio de los Corderos (1991)",
    rangoEdad: "R (Restringido)",
    autor: "Thomas Harris",
    reseña: "Un *thriller* psicológico magistral con actuaciones poderosas. Es una tensa batalla de ingenio entre el bien y el mal.",
    descripcionPelicula: "Una joven cadete del FBI debe entrevistar a un brillante pero peligroso psiquiatra caníbal, el Dr. Hannibal Lecter, para obtener pistas sobre un asesino en serie activo.",
    recomendacion: "Esencial dentro del género *thriller* de suspense y misterio.",
    detallesPelicula: "Dirigida por Jonathan Demme. Ganadora de los 'Cinco Grandes' Premios de la Academia (Película, Director, Actor, Actriz, Guion).",
    duracionPelicula: "1h 58m",
    imagenURL: "https://ejemplo.com/imagenes/el-silencio-de-los-corderos.jpg"
  },
  {
    id: 18,
    nombre: "Trainspotting (1996)",
    rangoEdad: "R (Restringido)",
    autor: "Irvine Welsh",
    reseña: "Una película cruda, estilizada y llena de energía. Es un retrato sin adornos de la adicción y la desilusión juvenil.",
    descripcionPelicula: "La vida de un grupo de jóvenes heroinómanos en la Edimburgo de la década de 1980, centrándose en el personaje de Mark Renton, quien intenta rehabilitarse.",
    recomendacion: "Para un público que aprecia el cine con un estilo visual fuerte y una narrativa no convencional.",
    detallesPelicula: "Dirigida por Danny Boyle. Famosa por su banda sonora y su estilo 'Britpop'.",
    duracionPelicula: "1h 33m",
    imagenURL: "https://ejemplo.com/imagenes/trainspotting.jpg"
  },
  {
    id: 19,
    nombre: "La Lista de Schindler (1993)",
    rangoEdad: "R (Restringido)",
    autor: "Thomas Keneally",
    reseña: "Una obra maestra histórica. Es una película desgarradora y conmovedora sobre la humanidad en medio del Holocausto.",
    descripcionPelicula: "Oskar Schindler, un empresario alemán y miembro del Partido Nazi, salva la vida de más de mil refugiados judíos durante el Holocausto.",
    recomendacion: "Una película esencial sobre un período histórico oscuro, por su valor testimonial y artístico.",
    detallesPelicula: "Dirigida por Steven Spielberg. Ganadora de 7 Premios de la Academia (incluyendo Mejor Película). Filmada principalmente en blanco y negro.",
    duracionPelicula: "3h 15m",
    imagenURL: "https://ejemplo.com/imagenes/la-lista-de-schindler.jpg"
  },
  {
    id: 20,
    nombre: "Desayuno con Diamantes (1961)",
    rangoEdad: "NR (No Clasificado, apta para toda la familia)",
    autor: "Truman Capote",
    reseña: "Una película elegante y encantadora que define el estilo de su época. Audrey Hepburn es icónica en su papel de Holly Golightly.",
    descripcionPelicula: "Una joven neoyorquina de espíritu libre y algo excéntrica busca un hombre rico con el que casarse, pero su vida se complica al conocer a un escritor que se muda a su edificio.",
    recomendacion: "Un clásico atemporal del romance y la comedia, ideal para los fans de Audrey Hepburn.",
    detallesPelicula: "Dirigida por Blake Edwards. La banda sonora ganó un Premio de la Academia por 'Moon River'.",
    duracionPelicula: "1h 55m",
    imagenURL: "https://ejemplo.com/imagenes/desayuno-con-diamantes.jpg"
  },
];